using AbpUpdateHelper.Services;

namespace AbpUpdateHelper.FileGroupActions
{
    public class FileGroupActionProjectFileOnly : IFileGroupAction
    {
        public void Run(FileGroup fileGroup, string destinationFolder)
        {
            fileGroup.CopyProjectFile(destinationFolder);
        }

        public bool Match(FileGroup fileGroup)
        {
            if (fileGroup.ProjectFile == null)
            {
                return false;
            }

            if (fileGroup.NewAbpFile == null && fileGroup.CurrentAbpFile == null && fileGroup.ProjectFile != null)
            {
                return true;
            }

            if (fileGroup.NewAbpFile != null && fileGroup.CurrentAbpFile != null)
            {
                if (fileGroup.NewAbpFile.IsAutoGenerated())
                {
                    return false;
                }

                if (AbpFileHelper.FilesAreEqual(fileGroup.NewAbpFile.File, fileGroup.CurrentAbpFile.File))
                {
                    return true;
                }
            }

            return false;
        }
    }
}